INDEED_PUBLISHER_ID = "6324424179656377"
INDEED_API_BASE_URL = "http://api.indeed.com/ads/apisearch?"
INDEED_API_VERSION = 2
INDEED_JOBS_FROMAGE = 30 #fetch jobs will expire in FROMAGE days

INDEED_JOBS_DEFAULT_COUNTRY = "CA"
INDEED_JOBS_DEFAULT_LOCATION = "Alberta"
INDEED_JOBS_DEFAULT_LIMIT = 2000
INDEED_JOBS_DEFAULT_SORTING = "date"
